version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: file-server-nginx
    ports:
      - "4040:80"
      - "4043:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./uploads:/var/www/static
      - ./frontend:/var/www/frontend
    depends_on:
      - api
    networks:
      - file-server-network
    restart: unless-stopped

  api:
    build: ./api
    container_name: file-server-api
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - GO_ENV=production
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - JWT_SECRET=${JWT_SECRET}
      - DEFAULT_CLIENT=${DEFAULT_CLIENT:-shared}
      - USER=${USER:-Sofmar}
      - PASSWORD=${PASSWORD:-s17052006}
      - PORT=3000
    networks:
      - file-server-network
    restart: unless-stopped

volumes:
  uploads:
    driver: local

networks:
  file-server-network:
    driver: bridge